repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-merge-conflict
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
    -   id: prettier
        types: [javascript]
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.23.1'
    hooks:
    -   id: eslint
        additional_dependencies:
          - eslint@8.23.1
          - eslint-config-standard@17.0.0
          - eslint-plugin-import@2.26.0
          - eslint-plugin-n@15.3.0
          - eslint-plugin-promise@6.0.1
          - eslint-config-prettier@8.5.0
