
export const purple_dark = '#6a006a'
export const purple_medium = '#a958a5'
export const purple_light = '#c481fb'
export const orange = '#ffa500'
export const gold = '#daa520'
export const red_dark = '#8e2430'
export const red_light = '#f94343'
export const blue_dark = '#3b5998'
export const cyan = '#5780cd'
export const blue_light = '#ace9e7'
export const aqua = '#33a1ee'
export const pink = '#ff9dbb'
export const green_dark = '#2ac075'
export const green_light = '#a1ee33'
export const white = '#f9f9f6'
export const cream = '#ffdab9'
