version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/python:3.10.7-node
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - restore_cache:
          key: pre-commit-{{ checksum ".pre-commit-config.yaml" }}

      - run:
          command: npm install
          name: Install dependencies
      - run:
          command: pip install pre-commit
          name: Install pre-commit

      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}
      - save_cache:
          paths:
            - "~/.cache/pre-commit"
          key: pre-commit-{{ checksum ".pre-commit-config.yaml" }}
      - run:
          command: pre-commit run --color=always --all-files
          name: Linting

workflows:
  lint_my_code:
    jobs:
      - lint
